/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_18 (
    input [1:0] alufn,
    input z,
    input n,
    input v,
    output reg [15:0] lastSum
  );
  
  
  
  always @* begin
    lastSum[1+14-:15] = 1'h0;
    
    case (alufn)
      2'h1: begin
        lastSum[0+0-:1] = z;
      end
      2'h2: begin
        lastSum[0+0-:1] = n ^ v;
      end
      2'h3: begin
        lastSum[0+0-:1] = z | (n ^ v);
      end
      default: begin
        lastSum[0+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
